export const projectsData = [
    {
      id: 1,
      title: "Eco-Friendly Smart Home",
      client: "Green Living Inc.",
      deliveryMethod: "Design & Build",
      completionDate: "June 10, 2023",
      location: "San Francisco, CA",
      sector: "Residential",
      markets: "Sustainable Housing",
      description:
        "An energy-efficient smart home designed with solar panels, rainwater harvesting, and modern automation for a sustainable lifestyle.",
      highlights: [
        "100% solar-powered with battery backup.",
        "Automated lighting and climate control.",
        "Rainwater harvesting and greywater recycling.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp", // Add image URL later
    },
    {
      id: 2,
      title: "Downtown Business Plaza",
      client: "Urban Developers Group",
      deliveryMethod: "Turnkey Project",
      completionDate: "September 15, 2022",
      location: "Chicago, IL",
      sector: "Commercial",
      markets: "Corporate Offices",
      description:
        "A modern business plaza featuring office spaces, retail outlets, and a multi-level parking facility.",
      highlights: [
        "State-of-the-art office infrastructure.",
        "Integrated shopping and leisure areas.",
        "Advanced security and surveillance system.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 3,
      title: "Highway Bridge Expansion",
      client: "State Transportation Department",
      deliveryMethod: "Public-Private Partnership",
      completionDate: "November 30, 2024",
      location: "Dallas, TX",
      sector: "Infrastructure",
      markets: "Transportation",
      description:
        "A major highway bridge expansion project aimed at reducing traffic congestion and improving connectivity.",
      highlights: [
        "Use of high-strength, low-maintenance materials.",
        "Pedestrian and bicycle lanes for added accessibility.",
        "Designed to withstand extreme weather conditions.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 4,
      title: "Luxury Hotel & Resort",
      client: "Global Hospitality Group",
      deliveryMethod: "Design-Bid-Build",
      completionDate: "July 20, 2025",
      location: "Miami, FL",
      sector: "Hospitality",
      markets: "Luxury Resorts",
      description:
        "A five-star beachfront resort with world-class amenities, including an infinity pool, spa, and gourmet dining.",
      highlights: [
        "Sustainable architecture with eco-friendly materials.",
        "Exclusive beachfront access and luxury suites.",
        "Smart technology integration for guest convenience.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 5,
      title: "Metro Rail Station Upgrade",
      client: "City Transit Authority",
      deliveryMethod: "Government Contract",
      completionDate: "April 5, 2024",
      location: "Seattle, WA",
      sector: "Public Infrastructure",
      markets: "Urban Transport",
      description:
        "Renovation and expansion of a metro rail station to accommodate increasing passenger flow and improve transit efficiency.",
      highlights: [
        "Modernized ticketing and security systems.",
        "Accessibility enhancements for disabled passengers.",
        "Integration with bike-sharing and bus networks.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 6,
      title: "Affordable Housing Project",
      client: "State Housing Authority",
      deliveryMethod: "Non-Profit Initiative",
      completionDate: "August 12, 2023",
      location: "Denver, CO",
      sector: "Residential",
      markets: "Affordable Housing",
      description:
        "A large-scale affordable housing project providing quality homes for low-income families.",
      highlights: [
        "Eco-friendly construction with low-cost materials.",
        "Community centers and recreational facilities.",
        "Energy-efficient homes with low maintenance costs.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 7,
      title: "Automobile Manufacturing Plant",
      client: "Future Auto Corp.",
      deliveryMethod: "Industrial Design-Build",
      completionDate: "December 1, 2026",
      location: "Detroit, MI",
      sector: "Industrial",
      markets: "Manufacturing",
      description:
        "A high-tech automobile manufacturing plant specializing in electric vehicle production.",
      highlights: [
        "Automated production lines with AI integration.",
        "Sustainable factory design with zero emissions.",
        "On-site renewable energy sources.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 8,
      title: "Medical Research Center",
      client: "National Health Foundation",
      deliveryMethod: "Public-Private Partnership",
      completionDate: "October 22, 2025",
      location: "Boston, MA",
      sector: "Healthcare",
      markets: "Medical Infrastructure",
      description:
        "A state-of-the-art research center dedicated to medical innovation and biotechnology advancements.",
      highlights: [
        "Cutting-edge laboratory spaces with advanced equipment.",
        "Collaborative environment for global researchers.",
        "Sustainability-focused building design.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 9,
      title: "International Airport Expansion",
      client: "Federal Aviation Authority",
      deliveryMethod: "Mega Infrastructure Project",
      completionDate: "May 18, 2027",
      location: "Atlanta, GA",
      sector: "Transportation",
      markets: "Airports & Aviation",
      description:
        "An expansion project adding new terminals, runways, and passenger lounges to one of the busiest airports in the world.",
      highlights: [
        "Smart airport technology with automated check-ins.",
        "Increased runway capacity for international flights.",
        "Sustainable architecture reducing environmental impact.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
    {
      id: 10,
      title: "Data Center Construction",
      client: "Tech Giants Inc.",
      deliveryMethod: "Turnkey Data Center Project",
      completionDate: "January 15, 2026",
      location: "Silicon Valley, CA",
      sector: "Technology",
      markets: "Cloud Computing & Data Storage",
      description:
        "A next-generation data center designed to support high-performance computing and cloud services.",
      highlights: [
        "AI-powered cooling systems for energy efficiency.",
        "Highly secure facility with biometric access.",
        "Scalable architecture for future technology growth.",
      ],
      image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    },
  ];
  