export const projectsData = [
    {
      id: 1,
      title: "Eco-Friendly Smart Home",
      client: "pinjamal hirani ji",
      deliveryMethod: "Design & Build",
      completionDate: "June 10, 2023",
      location: "Milanpur",
      sector: "Residential",
      markets: "Sustainable Housing",
      description:
        "A well-structured and secure warehouse designed to support efficient storage, inventory management, and seamless logistics operations. Built with high-quality materials, ensuring durability, safety, and accessibility for smooth handling of goods.",
        highlights:[
          "✅ Spacious Storage – Ample capacity for various types of inventory",
          "✅ Advanced Security – CCTV surveillance, access control, and fire safety.",
          "✅ Easy Accessibility – Well-planned entry/exit points for smooth loading/unloading.",
          "✅ Durable Construction – Built with high-grade materials for longevity.",
          "✅ Optimized Layout – Efficient space utilization for streamlined operations.",
          "✅ Sustainable Features – Energy-efficient lighting and ventilation options."
        ],
        
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741617023/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/e8prkaa2m3piecqdv7fa.jpg", // Add image URL later
    },
    {
      id: 2,
      title: "Comercial Complex",
      client: "Mr chandumal Tharwani",
      deliveryMethod: "Turnkey Project",
      completionDate: "September 15, 2024",
      location: "Ganj,Betul",
      sector: "Commercial",
      markets: "Corporate Offices",
      description:
        "A modern and well-designed commercial complex offering premium spaces for businesses, retail stores, and offices. Built with high-quality infrastructure, excellent connectivity, and advanced facilities to ensure a seamless business experience.",
      highlights: [
        "✅ Prime Location – Strategically situated for maximum visibility and accessibility.",
        "✅ Spacious Units – Flexible office and retail spaces to suit various business needs.",
        "✅ Modern Infrastructure – High-speed elevators, power backup, and advanced safety measures.",
        "✅ Ample Parking – Dedicated parking spaces for visitors and business owners.",
        "✅ Sustainable Design – Energy-efficient lighting and eco-friendly construction.",
        "✅ Security & Surveillance – 24/7 CCTV monitoring and access control for safety."
      ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741618083/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/ftsmplsjhizlnbdmpfmu.jpg",
    },
    {
      id: 3,
      title: "Bussiness",
      client: "Mr aman mehman",
      deliveryMethod: "SelfOwn",
      completionDate: "November 30, 2024",
      location: "Kosmi,Betul",
      sector: "Infrastructure",
      markets: "Transportation",
      description:
        "A well-structured and secure warehouse designed to support efficient storage, inventory management, and seamless logistics operations. Built with high-quality materials, ensuring durability, safety, and accessibility for smooth handling of goods.",
        highlights :[
          "✅ Spacious Storage – Ample capacity for various types of inventory",
          "✅ Advanced Security – CCTV surveillance, access control, and fire safety.",
          "✅ Easy Accessibility – Well-planned entry/exit points for smooth loading/unloading.",
          "✅ Durable Construction – Built with high-grade materials for longevity.",
          "✅ Optimized Layout – Efficient space utilization for streamlined operations.",
          "✅ Sustainable Features – Energy-efficient lighting and ventilation options."
        ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741618968/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/sn7pxy6ybveyigkfimrq.jpg",
    },
    {
      id: 4,
      title: "WareHouse",
      client: "Mohan sahu ji",
      deliveryMethod: "Design-Bid-Build",
      completionDate: "July 20, 2024",
      location: "Chhindwada",
      sector: "Hospitality",
      markets: "Luxury Resorts",
      description:
        "A well-structured and secure warehouse designed to support efficient storage, inventory management, and seamless logistics operations. Built with high-quality materials, ensuring durability, safety, and accessibility for smooth handling of goods.",
      highlights: [
        "✅ Spacious Storage – Ample capacity for various types of inventory",
  "✅ Advanced Security – CCTV surveillance, access control, and fire safety.",
  "✅ Easy Accessibility – Well-planned entry/exit points for smooth loading/unloading.",
  "✅ Durable Construction – Built with high-grade materials for longevity.",
  "✅ Optimized Layout – Efficient space utilization for streamlined operations.",
  "✅ Sustainable Features – Energy-efficient lighting and ventilation options.",
      ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741619507/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/yv7glcowqnvkiety4ccv.jpg",
    },
    {
      id: 5,
      title: "Complex",
      client: "Malviya Ji",
      deliveryMethod: "Design and Build",
      completionDate: "April 5, 2024",
      location: "azar chowk bhaisdehi",
      sector: "Public Infrastructure",
      markets: "Urban Transport",
      description:
        "A modern and well-designed commercial complex offering premium spaces for businesses, retail stores, and offices. Built with high-quality infrastructure, excellent connectivity, and advanced facilities to ensure a seamless business experience.",
      highlights: [
         "✅ Spacious Storage – Ample capacity for various types of inventory",
  "✅ Advanced Security – CCTV surveillance, access control, and fire safety.",
  "✅ Easy Accessibility – Well-planned entry/exit points for smooth loading/unloading.",
  "✅ Durable Construction – Built with high-grade materials for longevity.",
  "✅ Optimized Layout – Efficient space utilization for streamlined operations.",
  "✅ Sustainable Features – Energy-efficient lighting and ventilation options.",
      ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741619761/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/canzaabqzrsu8vr8kz9p.jpg",
    },
    {
      id: 6,
      title: "Residential Complex",
      client: "Mr Anil Kumar Hirani",
      deliveryMethod: "Non-Profit Initiative",
      completionDate: "August 12, 2023",
      location: "Ganj Betul/",
      sector: "Residential",
      markets: "Affordable Housing",
      description:
        "A premium residential complex offering modern amenities, spacious apartments, and a serene environment. Designed for comfort, security, and convenience, providing a perfect living experience for families and individuals.",
        highlights: [
          "✅ Prime Location – Well-connected to schools, hospitals, and shopping centers.",
          "✅ Spacious Apartments – Well-designed layouts with ample natural light and ventilation.",
          "✅ Modern Amenities – Gym, swimming pool, clubhouse, and children's play area.",
          "✅ 24/7 Security – CCTV surveillance, gated community, and secure access control.",
          "✅ Green Spaces – Landscaped gardens, walking tracks, and eco-friendly design.",
          "✅ Power Backup – Uninterrupted electricity supply for all essential services.",
          "✅ Ample Parking – Dedicated parking for residents and visitors."
        ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741621203/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/lm5a2rnmz5dczbdncvt9.jpg",
    },
    {
      id: 7,
      title: "Luxury House",
      client: "shantilal verma ji",
      deliveryMethod: "Design-Build",
      completionDate: "December 1, 2024",
      location: "Chhindwara Madhya Pradesh",
      sector: "Industrial",
      markets: "Manufacturing",
  
        description: "A sophisticated and elegantly designed luxury house offering top-tier amenities, premium architecture, and an opulent living experience. Designed for those who seek comfort, style, and exclusivity.",
        highlights: [
          "✅ Prime Location – Situated in a prestigious neighborhood with excellent connectivity.",
          "✅ Spacious Interiors – Expansive living areas with high ceilings and premium finishes.",
          "✅ Smart Home Features – Integrated automation for lighting, security, and climate control.",
          "✅ Private Swimming Pool – Enjoy resort-style luxury with a personal pool.",
          "✅ High-Security System – 24/7 surveillance, biometric access, and gated premises.",
          "✅ Designer Landscaping – Beautifully crafted gardens and outdoor seating areas.",
          "✅ Luxury Amenities – Home theater, gym, spa, and entertainment lounge.",
          "✅ Premium Materials – Imported marble flooring, designer fittings, and custom woodwork.",
          "✅ Eco-Friendly Features – Solar power, rainwater harvesting, and energy-efficient lighting.",
          "✅ Ample Parking – Dedicated garage with space for multiple vehicles."
        ],
      image: "https://res.cloudinary.com/dhbvmqhmg/image/upload/v1741621611/4images/OUR%20PROJECTS%20SECTION/COMPLETE%20PROJECTS/l8qgkdw53sporhplwakh.jpg",
    },
    // {
    //   id: 8,
    //   title: "Medical Research Center",
    //   client: "National Health Foundation",
    //   deliveryMethod: "Public-Private Partnership",
    //   completionDate: "October 22, 2025",
    //   location: "Boston, MA",
    //   sector: "Healthcare",
    //   markets: "Medical Infrastructure",
    //   description:
    //     "A state-of-the-art research center dedicated to medical innovation and biotechnology advancements.",
    //   highlights: [
    //     "Cutting-edge laboratory spaces with advanced equipment.",
    //     "Collaborative environment for global researchers.",
    //     "Sustainability-focused building design.",
    //   ],
    //   image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    // },
    // {
    //   id: 9,
    //   title: "International Airport Expansion",
    //   client: "Federal Aviation Authority",
    //   deliveryMethod: "Mega Infrastructure Project",
    //   completionDate: "May 18, 2027",
    //   location: "Atlanta, GA",
    //   sector: "Transportation",
    //   markets: "Airports & Aviation",
    //   description:
    //     "An expansion project adding new terminals, runways, and passenger lounges to one of the busiest airports in the world.",
    //   highlights: [
    //     "Smart airport technology with automated check-ins.",
    //     "Increased runway capacity for international flights.",
    //     "Sustainable architecture reducing environmental impact.",
    //   ],
    //   image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    // },
    // {
    //   id: 10,
    //   title: "Data Center Construction",
    //   client: "Tech Giants Inc.",
    //   deliveryMethod: "Turnkey Data Center Project",
    //   completionDate: "January 15, 2026",
    //   location: "Silicon Valley, CA",
    //   sector: "Technology",
    //   markets: "Cloud Computing & Data Storage",
    //   description:
    //     "A next-generation data center designed to support high-performance computing and cloud services.",
    //   highlights: [
    //     "AI-powered cooling systems for energy efficiency.",
    //     "Highly secure facility with biometric access.",
    //     "Scalable architecture for future technology growth.",
    //   ],
    //   image: "https://www.livehome3d.com/assets/img/win/realistic-lighting@2x.webp",
    // },
  ];
  